spring:
  application:
    name: trading-service

  profiles:
    active: dev

  # 使用H2内存数据库，便于开发测试
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:trading_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # Redis暂时禁用，简化启动
  # redis:
  #   host: localhost
  #   port: 6379
  #   password: redis123456

  cache:
    type: simple  # 使用简单缓存替代Redis

server:
  port: 8083
  servlet:
    context-path: /trading-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.quant.trading: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"